import { useCallback, useState } from 'react'
import { Form } from 'antd'
import { SignupMutationFn, useSignupMutation } from 'graphql/autogenerated'
export interface ISignUpByEmail {
  onSignup: SignupMutationFn
}

export const useSignUp = (props: ISignUpByEmail) => {
  const [formSignUp] = Form.useForm()
  const [initialUserState] = useState({
    email: '',
    password: '',
  })
  const [handleSignup, { data, loading, error }] = useSignupMutation({ onError: () => {} })
  const onSignup = useCallback(
    values => {
      handleSignup({
        variables: {
          input: {
            email: values.email,
            password: values.password,
            // mobile: values.mobile,
          },
        },
      })
    },
    [handleSignup],
  )

  return {
    formSignUp,
    onSignup,
    initialUserState,
    data,
    loading,
    error,
  }
}
