import { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  ignoreNoDocuments: true,
  generates: {
    'src/graphql/autogenerated.tsx': {
      schema: 'src/graphql/schema.graphql',
      documents: './src/graphql/api-schema/**/*.graphql',
      plugins: ['typescript', 'typescript-operations', 'typescript-react-apollo'],
      config: {
        withHooks: true,
        withComponent: false,
      },
    },
  },
}

export default config
