version: '3.4'

services:
  app:
    image: nginx:1.19.8-alpine
    container_name: sv-admin-reactjs
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx/admin-dashboard.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 3001:80
    # command: [nginx-debug, '-g', 'daemon off;']
    # restart: unless-stopped
