/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  MetaSerializers: {
    id?: string
    jsonLd?: string
    view?: number
    like?: number
    updated?: string
    timestamp?: string
  }
  Article: {
    id?: string
    meta?: definitions['MetaSerializers']
    id_audio?: string
    blog_title?: string
    blog_slug?: string
    user?: string
    blog?: string
    title?: string
    slug: string
    excerpt?: string
    content?: string
    resource?: string
    ping?: boolean
    type?: 1 | 2 | 3 | 4 | 5
    status?: string
    thumbnail?: string
    updated?: string
    timestamp?: string
    tags?: string[]
    categories?: string[]
  }
  Blog: {
    id?: string
    meta: definitions['MetaSerializers']
    user?: string
    title?: string
    slug: string
    excerpt?: string
    content?: string
    ping?: boolean
    status?: string
    updated?: string
    timestamp?: string
  }
  CategorySerializers: {
    id?: string
    meta?: definitions['MetaSerializers']
    title?: string
    slug: string
    description?: string
    status?: string
    isDeleted?: boolean
    updated?: string
    timestamp?: string
  }
  Comment: {
    id?: string
    article_thumbnail?: string
    article_slug?: string
    parrentId?: string
    user?: string
    view?: number
    like?: number
    content?: string
    updated?: string
    timestamp?: string
    article?: string
  }
  Media: {
    id?: string
    file?: string
    data?: string
    path?: string
    name?: string
    type?: 1 | 2
    updated?: string
    timestamp?: string
  }
  MenuSerializers: {
    id?: string
    name?: string
    html?: string
    status?: string
    isDeleted?: boolean
    type: 1 | 2 | 3 | 4 | 5
    updated?: string
    timestamp?: string
  }
  Setting: {
    id?: string
    key: string
    value?: string
    option?: string
    isDeleted?: boolean
    default?: string
  }
  TagSerializers: {
    id?: string
    title?: string
    slug: string
    content?: string
    isDeleted?: boolean
    updated?: string
    timestamp?: string
    meta?: string
  }
  User: {
    id?: string
    password: string
    last_login?: string
    groups?: string[]
    user_permissions?: string[]
    meta?: definitions['MetaSerializers']
    blog?: definitions['Blog']
    updated?: string
    timestamp?: string
    /**
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string
    first_name?: string
    last_name?: string
    email?: string
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean
    date_joined?: string
    avatar?: string
  }
  TokenObtainPair: { email: string; password: string }
  TokenRefresh: { refresh: string }
  TokenVerify: { token: string }
  Widget: {
    id?: string
    meta: definitions['MetaSerializers']
    type?: string
    title?: string
    isDeleted?: boolean
    image?: string
    url?: string
    size: string
    updated?: string
    timestamp?: string
  }
}
